---
title: "Belarus COVID-19"
author: "Yolanda Feng"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Set up and read data -->

```{r, echo=FALSE}
# set working directory

setwd("C:/ZZZ/Study/2020 Spring/COVID-19")

# read data file

global <- read.csv("csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
global_death <- read.csv("csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
global_recover <- read.csv("csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
us <- read.csv("csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
us_death <- read.csv("csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")
```

<!-- seperate Belarus data -->

```{r, echo=FALSE}
# creat flight df
flight <- subset(global, Country.Region == c("Belarus","US"))
flight_death <- subset(global_death, Country.Region == c("Belarus","US"))
flight_recover <- subset(global_recover, Country.Region == c("Belarus","US"))

# creat state df
state <- subset(us, Province_State == c("Illinois","California"))
state_death <- subset(us_death, Province_State == c("Illinois","California"))

# standerdize format
flight <- flight[,-c(1,3,4)]
flight_death <- flight_death[,-c(1,3,4)]

# creat merged df
allpassby <- merge(flight, state)
allpassby_death <- merge(flight_death, state_death)
```